services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5174:5173"
    depends_on:
      - backend
    networks:
      - cinephoria-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5001:5000"
    depends_on:
      - mysql-db
      - mongodb-db
    command: >
      sh -c "
        while ! nc -z mysql-db ${MYSQL_PORT}; do sleep 1; done;
        while ! nc -z mongodb-db ${MONGODB_PORT}; do sleep 1; done;
        /usr/src/app/node_modules/.bin/nodemon server.js
      "
    environment:
      - NODE_ENV=development
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_NAME=${MONGODB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MONGODB_PORT=${MONGODB_PORT}
      - MYSQL_PORT=${MYSQL_PORT}
    networks:
      - cinephoria-network

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - cinephoria-network

  mongodb-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - cinephoria-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: ${MYSQL_HOST}
            port: ${MYSQL_PORT}
            user: ${MYSQL_USER}
            password: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - cinephoria-network

networks:
  cinephoria-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
  mysql-data:
  mongo-data:
